version: "3.9"
services:
  app:
    build:
      context: .
    container_name: blogging-app
    restart: always
    ports:
      - "5000:${APP_PORT}"
    environment:
      APP_NAME: ${APP_NAME}
      FLASK_DEBUG: ${APP_DEBUG:-false}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_CONNECTION_STRING: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_APP_NAME}:27017
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
      SECRET_KEY: ${APP_SECRET_KEY}
    volumes:
      - ./src:/app
    depends_on:
      - database

  database:
    image: mongo
    container_name: ${MONGO_APP_NAME}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_APP_NAME}:27017/
    depends_on:
      - database
